### ISSUE TITLE
keyboardAppearance prop not working

### ISSUE THREAD

**Issue by OscarBlackbullion** [CaioQuirinoMedeiros/react-native-currency-input#37] opened 2024-08-01 15:13 UTC
The `keyboardAppearance` prop from `TextInput` doesn't appear to be working - trying to set it as `dark` and the keyboard is still showing as `light`.

```
              <CurrencyInput
                returnKeyType='done'
                value={currencyVal}
                onChangeValue={(val) => {
                  console.log(val);
                }}
                maxLength={8}
                delimiter=','
                minValue={0}
                precision={0}
                prefix='£'
                keyboardAppearance='dark'
              />
```

<img width="343" alt="Screenshot 2024-08-01 at 16 13 57" src="https://github.com/user-attachments/assets/6ba04991-b7f3-454a-8a53-9996cb5573c1">

**Comment by CaioQuirinoMedeiros** [comment] 2024-08-01 15:35
This library does nothing with this `keyboardAppearance`. Show me some evidence that the problem is here or I'll be closing the issue

**Comment by OscarBlackbullion** [comment] 2024-08-01 15:57
Perhaps this shouldn't be the case, but in VSCode it seems to expect that this prop can be passed - I assumed it would then just be passed down to the `TextInput` component used within the `CurrencyInput` component

<img width="798" alt="Screenshot 2024-08-01 at 16 55 41" src="https://github.com/user-attachments/assets/7327d03f-3730-4058-8656-3ac79e14280a">

https://reactnative.dev/docs/textinput#keyboardappearance-ios

**Comment by CaioQuirinoMedeiros** [comment] 2024-08-01 16:02
So even assuming that, you still opened a issue here... I'm closing this issue until any prove is shown

**Closed as completed by CaioQuirinoMedeiros** 2024-08-01 16:02 UTC
